/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package ui.MarketingTeam;

import java.awt.CardLayout;
import model.Business.Business;
import ui.MarketingTeam.ManageSuppliersJPanel;
import javax.swing.JPanel;
import model.UserAccountManagement.UserAccount;
import model.UserAccountManagement.UserAccountDirectory;
import ui.SalesPerson.AddOrderJPanel;

/**
 *
 * @author kal
 */
public class MarketingManagerWorkAreaJPanel1 extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    String setting;
    UserAccount userAccount;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public MarketingManagerWorkAreaJPanel1(Business b, JPanel clp,String setting, UserAccount userAccount) {

        business = b;
        this.CardSequencePanel = clp;
        initComponents();
        this.setting=setting;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPriceperfanalysis = new javax.swing.JButton();
        btnPerfRep = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 243, 224));
        setForeground(new java.awt.Color(51, 51, 51));

        btnPriceperfanalysis.setBackground(new java.awt.Color(142, 107, 57));
        btnPriceperfanalysis.setFont(getFont());
        btnPriceperfanalysis.setForeground(new java.awt.Color(255, 255, 255));
        btnPriceperfanalysis.setText("Price Performance Analysis");
        btnPriceperfanalysis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPriceperfanalysis.setMaximumSize(new java.awt.Dimension(145, 40));
        btnPriceperfanalysis.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPriceperfanalysis.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPriceperfanalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceperfanalysisIdentifyEventsActionPerformed(evt);
            }
        });

        btnPerfRep.setBackground(new java.awt.Color(142, 107, 57));
        btnPerfRep.setFont(getFont());
        btnPerfRep.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfRep.setText("Performance Reports");
        btnPerfRep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerfRep.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerfRep.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerfRep.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerfRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfRepActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(250, 243, 224));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Marketing ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnPriceperfanalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnPerfRep, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPriceperfanalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerfRep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPriceperfanalysisIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceperfanalysisIdentifyEventsActionPerformed
  
        ManagePricingJPanel managePricingJPanel = new ManagePricingJPanel(CardSequencePanel, business, userAccount);
        CardSequencePanel.add("ManageSuppliersJPanel", managePricingJPanel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
}//GEN-LAST:event_btnPriceperfanalysisIdentifyEventsActionPerformed

    private void btnPerfRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfRepActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
        PerfeormanceJPanel perfeormanceJPanel = new PerfeormanceJPanel(CardSequencePanel, business, userAccount);
        CardSequencePanel.add("PerfeormanceJPanel", perfeormanceJPanel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
}//GEN-LAST:event_btnPerfRepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerfRep;
    private javax.swing.JButton btnPriceperfanalysis;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
