/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package ui.SalesPerson;

import model.Business.Business;
import model.CustomerManagement.CustomerProfile;
import model.SalesManagement.SalesPersonProfile;
//import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ManageSalesPersonOrders;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business.Business;
import model.CustomerManagement.CustomerProfile;
import model.SalesManagement.SalesPersonProfile;
import model.UserAccountManagement.UserAccount;
import model.UserAccountManagement.UserAccountDirectory;

/**
 *
 * @author kal
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    SalesPersonProfile salesperson;
    private CustomerProfile loggedInCustomer;
    String setting;

    /**
     * Creates new form UnitRiskWorkArea
     * @param b
     * @param spp
     * @param clp
     */

    public SalesPersonWorkAreaJPanel(Business b, SalesPersonProfile spp, JPanel clp,String setting) {

        business = b;
        this.CardSequencePanel = clp;
        this.setting=setting;
        salesperson = spp;
        initComponents();
       
        ArrayList<CustomerProfile> customerlist = business.getCustomerDirectory().getCustomerlist();
        if (customerlist.isEmpty()) {
            return;
        }
        
//        for (CustomerProfile c : customerlist) {
//            
//            customerNamejCombo.addItem(c.toString());
//            customerNamejCombo.setSelectedIndex(0);
//            
//
//    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmngOrders = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 243, 224));
        setForeground(new java.awt.Color(51, 51, 51));

        btnmngOrders.setBackground(new java.awt.Color(142, 107, 57));
        btnmngOrders.setFont(getFont());
        btnmngOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnmngOrders.setText("Manage Orders");
        btnmngOrders.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmngOrders.setMaximumSize(new java.awt.Dimension(200, 40));
        btnmngOrders.setMinimumSize(new java.awt.Dimension(20, 20));
        btnmngOrders.setPreferredSize(new java.awt.Dimension(240, 25));
        btnmngOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmngOrdersActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("                  SALES'S DASHBOARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnmngOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(55, 55, 55)
                .addComponent(btnmngOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(615, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmngOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmngOrdersActionPerformed
        // TODO add your handling code here:

//        ManageSalesPersonOrders iet = new ManageSalesPersonOrders(business, CardSequencePanel);
//
//        CardSequencePanel.add("FindResourceAsset", iet);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
           UserAccountDirectory uad = business.getUserAccountDirectory();
           
           
           AddOrderJPanel AOJ=new AddOrderJPanel(CardSequencePanel,  business,uad.findUserAccount(salesperson.getPerson().getPersonId()));
           CardSequencePanel.add("ManageVulns", AOJ);
           ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnmngOrdersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmngOrders;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void populatejCombobox(ArrayList<CustomerProfile> searchedCustomer) {
//        customerNamejCombo.removeAllItems();
//        for(CustomerProfile customer1: searchedCustomer){
//            customerNamejCombo.addItem(customer1.toString());
//            customerNamejCombo.setSelectedIndex(0);
//          
//        }
    }

}
