
package ui;

import model.MarketingManagement.MarketingPersonProfile;
import model.Business.Business;
import model.CustomerManagement.CustomerProfile;
import model.MarketModel.Channel;
import model.MarketModel.Market;
import model.MarketModel.MarketChannelAssignment;
import model.ProductManagement.SolutionOffer;
import model.Personnel.EmployeeProfile;
import model.Personnel.Profile;
import model.ProductManagement.Product;
import model.SalesManagement.SalesPersonProfile;
import model.OrderManagement.MasterOrderList;
import model.Supplier.Supplier;
import model.UserAccountManagement.UserAccount;
import model.UserAccountManagement.UserAccountDirectory;
import ui.MarketingTeam.MarketingManagerWorkAreaJPanel1;
import ui.SalesPerson.SalesPersonWorkAreaJPanel;
import javax.swing.JPanel;
import model.Business.ConfigureABusiness;
import model.ProductManagement.ProductCatalog;
import model.Supplier.SupplierDirectory;
import ui.MarketingTeam.MarketingManagerWorkAreaJPanel1;
import ui.SalesPerson.SalesPersonWorkAreaJPanel;
 

/**
 *
 * @author kal bugrara
 */
public class MainJFrame extends javax.swing.JFrame {

    Business business;
    SupplierDirectory suppliers;

    /**
     * Creates new form PricingMainFrame
     */

    public MainJFrame() {
        initComponents();
        business = ConfigureABusiness.initialize();
        suppliers = new SupplierDirectory();
        business.populateSuppliers();
        setSize(1100, 800);

        
        business.populateCustomersSalesMarketing();
    }

    public void insert(JPanel jpanel) {

    }
    
    public void populateSuppliers() {
  
    for (int supplierIndex = 1; supplierIndex <= 10; supplierIndex++) {
        
        Supplier currentSupplier = suppliers.newSupplier("Supplier" + supplierIndex);

        
        for (int productIndex = 1; productIndex <= 5; productIndex++) { 
            ProductCatalog pc = currentSupplier.getProductCatalog();

           
            Product p = pc.newProduct(
                "Product" + productIndex + "_Supplier" + supplierIndex,
                (int) (Math.random() * 1000), 
                (int) (Math.random() * 500 + 1000), 
                (int) (Math.random() * 800 + 500) 
            );
            
            
            p.setSupplier(currentSupplier);
            suppliers.addSupplier(currentSupplier);
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitHomeArea = new javax.swing.JSplitPane();
        actionsidejpanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        CardSequencePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actionsidejpanel.setBackground(new java.awt.Color(250, 243, 224));
        actionsidejpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        actionsidejpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 30));

        jLabel1.setText("User Name");
        actionsidejpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        UserNameTextField.setText("sales");
        UserNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextFieldActionPerformed(evt);
            }
        });
        actionsidejpanel.add(UserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        jLabel2.setText("Password");
        actionsidejpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));
        actionsidejpanel.add(PasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        SplitHomeArea.setLeftComponent(actionsidejpanel);

        CardSequencePanel.setBackground(new java.awt.Color(250, 243, 224));
        CardSequencePanel.setLayout(new java.awt.CardLayout());
        SplitHomeArea.setRightComponent(CardSequencePanel);

        getContentPane().add(SplitHomeArea, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

        String un = UserNameTextField.getText();
        String pw = PasswordTextField.getText();

        UserAccountDirectory uad = business.getUserAccountDirectory();

        UserAccount useraccount = uad.AuthenticateUser(un, pw);
        if (useraccount == null) {
            return;
        }
        SalesPersonWorkAreaJPanel salesworkarea;
        MarketingManagerWorkAreaJPanel1 marketingworkarea;
        String r = useraccount.getRole();
        Profile profile = useraccount.getAssociatedPersonProfile();
       
                if (profile instanceof SalesPersonProfile) {
                    SalesPersonProfile spp = (SalesPersonProfile) profile;
                    salesworkarea = new SalesPersonWorkAreaJPanel(business, spp, CardSequencePanel,"Sales");
                    CardSequencePanel.removeAll();
                    CardSequencePanel.add("Sales", salesworkarea);
                    populateSuppliers();
                    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

                }

                if (profile instanceof MarketingPersonProfile) {
                    marketingworkarea = new MarketingManagerWorkAreaJPanel1(business, CardSequencePanel,"Marketing", useraccount);
                    CardSequencePanel.removeAll();
                    CardSequencePanel.add("Marketing", marketingworkarea);
                    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

                }
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequencePanel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JSplitPane SplitHomeArea;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JPanel actionsidejpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables


}
